//! Differential test: the percentage mermaid labels each pie slice with.
//!
//! THE DIVERGENCE THIS PINS. `pie "Apples" : 40` drew `Apples` on the slice and no percentage
//! anywhere; mermaid draws `40%`. Found by `scripts/headtohead/drawn_text_diff.mjs`, which renders
//! both engines and diffs the drawn `<text>`: mermaid drew `["40%","30%","30%"]` that we did not.
//! The name is not lost — the legend beside the chart carries it, which is where mermaid puts it
//! too.
//!
//! ⚠️ THE ROUNDING IS NOT THE ONE RUST DEFAULTS TO, and that is the substance of this file. mermaid
//! rounds in JavaScript, where `Math.round(12.5)` is `13`. Rust's `{:.0}` rounds half to EVEN and
//! renders the same value `12`. The two rules agree on every round number, so an implementation
//! using `{:.0}` passes 40/30/30, 1/1/1 and 2/1 and is wrong only on an exact half.
//!
//! THE ORACLE is `tests/fixtures/mermaid_pie_percents.tsv`, generated by
//! `scripts/headtohead/pie_percent_battery.mjs` from the pinned 11.15.0 bundle. It carries
//! exact-half cases on purpose:
//!
//! ```text
//!   1,7    -> 13%,88%     1/8 is 12.5: half-up 13, half-to-even 12   <- discriminating
//!   1,39   -> 3%,98%      1/40 is 2.5: half-up 3,  half-to-even 2    <- discriminating
//!   3,5    -> 38%,63%     37.5 rounds to 38 under both rules
//! ```
//!
//! NOT ASSERTED HERE: our legend heading (`Legend`), which mermaid does not draw, and the legend's
//! own `A: 40 (40.0%)` entry against mermaid's `A [40]` under `showData`. Both are real differences
//! in a different element, measured in the same sweep, and folding them in would make this file fail
//! for reasons that have nothing to do with the slice percentage.

use std::{fs, path::Path};

struct Row {
    values: Vec<f64>,
    percents: Vec<String>,
}

fn fixture() -> Vec<Row> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/mermaid_pie_percents.tsv");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("fixture {} unreadable: {err}", path.display()));
    let rows: Vec<Row> = text
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .skip(1)
        .map(|line| {
            let mut columns = line.split('\t');
            let values = columns
                .next()
                .expect("values column")
                .split(',')
                .map(|value| value.parse().expect("numeric slice value"))
                .collect();
            let percents = columns
                .next()
                .expect("percents column")
                .split(',')
                .map(str::to_string)
                .collect();
            Row { values, percents }
        })
        .collect();
    assert!(rows.len() >= 8, "fixture holds only {} rows", rows.len());
    rows
}

/// Every `<text>` leaf that is a bare percentage, in document order.
fn drawn_percents(source: &str) -> Vec<String> {
    let svg = fm_render_svg::render_svg(&fm_parser::parse(source).ir);
    let mut out = Vec::new();
    let mut rest = svg.as_str();
    while let Some(start) = rest.find("<text") {
        rest = &rest[start..];
        let Some(open) = rest.find('>') else { break };
        let Some(close) = rest.find("</text>") else { break };
        let inner = rest[open + 1..close].trim();
        if !inner.is_empty()
            && inner.ends_with('%')
            && inner[..inner.len() - 1].chars().all(|c| c.is_ascii_digit())
        {
            out.push(inner.to_string());
        }
        rest = &rest[close + "</text>".len()..];
    }
    out
}

fn source_for(values: &[f64]) -> String {
    let mut source = String::from("pie title T\n");
    for (index, value) in values.iter().enumerate() {
        source.push_str(&format!("  \"S{index}\" : {value}\n"));
    }
    source
}

#[test]
fn every_slice_is_labelled_with_the_percentage_mermaid_draws() {
    let mut compared = 0;
    let mut divergent = Vec::new();
    for row in fixture() {
        compared += 1;
        let drawn = drawn_percents(&source_for(&row.values));
        if drawn != row.percents {
            divergent.push(format!(
                "{:?}: ours {drawn:?}, mermaid {:?}",
                row.values, row.percents
            ));
        }
    }
    assert!(compared >= 8, "only {compared} rows compared");
    assert!(
        divergent.is_empty(),
        "{} pie chart(s) label slices differently from mermaid 11.15.0:\n  {}",
        divergent.len(),
        divergent.join("\n  ")
    );
}

/// ⚠️ THE NEGATIVE CONTROL, AND THE REASON THE FIXTURE CONTAINS EXACT HALVES.
///
/// This asserts the fixture can still tell half-up from half-to-even. Without it, a battery
/// regenerated with only round numbers would leave the test above passing against a `{:.0}`
/// implementation — the assertions would all hold and the rounding rule would be unpinned.
#[test]
fn the_fixture_can_distinguish_the_two_rounding_rules() {
    let discriminating: Vec<_> = fixture()
        .into_iter()
        .filter(|row| {
            let total: f64 = row.values.iter().sum();
            row.values.iter().any(|value| {
                let percent = value / total * 100.0;
                // An exact half is where round-half-up and round-half-to-even part company.
                (percent.fract() - 0.5).abs() < 1e-9 && (percent.floor() as i64) % 2 == 0
            })
        })
        .collect();
    assert!(
        !discriminating.is_empty(),
        "the fixture has no exact-half case whose two roundings differ, so it cannot tell \
         Math.round from Rust's {{:.0}} and a wrong implementation would pass"
    );
    // And the recorded answer must be the half-UP one, or the oracle itself has drifted.
    for row in discriminating {
        let total: f64 = row.values.iter().sum();
        for (value, percent) in row.values.iter().zip(&row.percents) {
            let exact = value / total * 100.0;
            if (exact.fract() - 0.5).abs() < 1e-9 {
                let half_up = (exact + 0.5).floor() as i64;
                assert_eq!(
                    percent,
                    &format!("{half_up}%"),
                    "fixture disagrees with round-half-up on an exact half ({exact})"
                );
            }
        }
    }
}

/// CONTROL: the slice name must NOT vanish from the document. Replacing the label with a percentage
/// is only correct because the legend still carries the name — otherwise this would have traded a
/// missing percentage for a missing name.
#[test]
fn the_slice_names_are_still_drawn_somewhere() {
    let svg = fm_render_svg::render_svg(&fm_parser::parse(&source_for(&[40.0, 30.0, 30.0])).ir);
    for name in ["S0", "S1", "S2"] {
        assert!(
            svg.contains(name),
            "slice name {name} disappeared from the document entirely"
        );
    }
}
