// Ask the PINNED incumbent what a class METHOD row displays as — the half
// `class_generics_battery.mjs` deliberately left out — and write the answers down as the fixture
// `crates/fm-render-svg/tests/fixtures/mermaid_class_methods.tsv`.
//
// That earlier battery used attribute rows only, so its equality could be about the generics rewrite
// and nothing else. Methods add two more things to the same string, and both are open contracts:
// the ` : returnType` tail (bd-ci658 — mermaid writes `+f() : T`, we write `+f(): T`) and the
// `$`/`*` classifier, which mermaid does not put in the text AT ALL (bd-r2gll — it returns
// `text-decoration:underline;` / `font-style:italic;` in `cssStyle` instead, because UML underlines
// a static member and italicises an abstract one).
//
//   npm install --prefix scripts        # jsdom, already a declared devDependency there
//   node scripts/headtohead/class_method_battery.mjs
//
// ⚠️ NEEDS A DOM (DOMPurify); see diagram_db_probe.mjs.
//
// Columns, tab separated:
//   member      the method line as written inside `class Foo { … }`
//   classifier  mermaid's `$`/`*`, empty when there is none
//   display     mermaid's own `getDisplayDetails().displayText`
//   css         the `cssStyle` it returns beside that text — where the classifier actually lives
//
// The classifier columns are carried even though the test does not assert them yet: bd-r2gll is the
// open contract for turning `$`/`*` into styling, and a fixture that dropped the evidence would have
// to be regenerated before anyone could act on it.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { JSDOM } from 'jsdom';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-render-svg/tests/fixtures/mermaid_class_methods.tsv');

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="c"></div></body></html>', {
  runScripts: 'dangerously',
});
const w = dom.window;
const script = w.document.createElement('script');
script.textContent = fs.readFileSync(BUNDLE, 'utf8');
w.document.head.appendChild(script);
const mermaid = w.mermaid;
if (typeof mermaid?.parse !== 'function') {
  console.error('pinned bundle did not expose window.mermaid.parse');
  process.exit(1);
}
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });

const MEMBERS = [
  '+getName() String',
  '+getName()',
  '+set(x int, y int) void',
  '+set(a, b)',
  '+getItems() List~int~',
  '+m() Map~String, int~',
  '-privateMethod() void',
  '#protectedMethod() void',
  '~packageMethod() void',
  'unmarkedMethod() void',
  '+a.b.c() void',
  // The author writing their own colon. mermaid captures it INTO the return type and then draws a
  // second one, which is why these two rows exist: to record the quirk rather than discover it later.
  '+getName() : String',
  '+getName(): String',
  // Classifier rows — text and style, for bd-r2gll.
  '+getName()$ String',
  '+getName()* String',
  '+getName()$',
  '+getName()*',
];

const rows = [];
for (const member of MEMBERS) {
  const text = `classDiagram\nclass Foo {\n${member}\n}\n`;
  await mermaid.parse(text);
  const diagram = await mermaid.mermaidAPI.getDiagramFromText(text);
  const db = diagram.db ?? diagram.getDB();
  const classes = db.getClasses();
  const foo = classes.get ? classes.get('Foo') : classes.Foo;
  if (foo.methods.length !== 1) {
    console.error(`${member}: expected exactly one method, got ${foo.methods.length}`);
    process.exit(1);
  }
  const [method] = foo.methods;
  const details = typeof method.getDisplayDetails === 'function' ? method.getDisplayDetails() : {};
  rows.push([member, method.classifier ?? '', details.displayText ?? '', details.cssStyle ?? '']);
}

const banner = [
  '# GENERATED by scripts/headtohead/class_method_battery.mjs against mermaid 11.15.0 — do not hand-edit.',
  '# Each row is what the incumbent ACTUALLY displays for one method line of `class Foo { … }`.',
  ['# member', 'classifier', 'display', 'css'].join('\t'),
].join('\n');
fs.writeFileSync(OUT, `${banner}\n${rows.map((row) => row.join('\t')).join('\n')}\n`);
const classified = rows.filter((row) => row[1] !== '').length;
console.log(`${rows.length} methods -> ${OUT}`);
console.log(`  ${classified} carry a classifier, ${rows.length - classified} do not`);
