// Ask the PINNED incumbent how it parses every ER attribute spelling, and write the answers down as
// the fixture `crates/fm-parser/tests/fixtures/mermaid_er_attributes.tsv`.
//
// WHY A GENERATOR AND NOT A HAND-WRITTEN TABLE. mermaid's ER attribute is
// `type name [keys] ["comment"]`, and the KEYS ARE A LIST — `keys: ['PK','FK']` — which is easy to
// miss because a single-key diagram behaves identically either way. This parser carried one key and
// split the line on whitespace, so the token `PK,` from `string a PK, FK` matched no key and fell
// into the COMMENT branch: the row drew `FK string a PK,` (bd-nryyc). Two further facts nobody
// guesses, both measured here rather than assumed:
//
//   * the space-separated `PK FK` is REJECTED by mermaid's grammar, so only comma forms parse;
//   * mermaid renders the key cell with `attribute.keys.join()` — `Array.prototype.join` with NO
//     separator argument, which is `,` — so two keys are the single token `PK,FK`, never `PK FK`.
//     That is a token-level fact, and the cross-engine text gate compares tokens.
//
//   npm install --prefix scripts        # jsdom, already a declared devDependency there
//   node scripts/headtohead/er_attribute_battery.mjs
//
// ⚠️ NEEDS A DOM (DOMPurify); see diagram_db_probe.mjs.
//
// Columns, tab separated:
//   attribute  the attribute line as written inside `A { … }`
//   verdict    PARSED | REJECTED
//   type       mermaid's parsed `type`   — empty unless PARSED
//   name       mermaid's parsed `name`   — empty unless PARSED
//   keys       mermaid's `keys` array, comma-joined exactly as it draws them; empty when there are none
//   comment    mermaid's `comment`
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { JSDOM } from 'jsdom';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-parser/tests/fixtures/mermaid_er_attributes.tsv');

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="c"></div></body></html>', {
  runScripts: 'dangerously',
});
const w = dom.window;
const script = w.document.createElement('script');
script.textContent = fs.readFileSync(BUNDLE, 'utf8');
w.document.head.appendChild(script);
const mermaid = w.mermaid;
if (typeof mermaid?.parse !== 'function') {
  console.error('pinned bundle did not expose window.mermaid.parse');
  process.exit(1);
}
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });

const ATTRIBUTES = [
  // No key.
  'string plain',
  'int count',
  'string[] tags',
  'varchar(99) blob',
  // One key, the case a single-key field models correctly.
  'string a PK',
  'string b FK',
  'string c UK',
  'string d pk',
  // Composite keys — the defect.
  'string e PK, FK',
  'string f PK,FK',
  'string g UK, PK, FK',
  'string h FK, PK',
  // Keys with a comment, both orders of appearance.
  'string i PK "the id"',
  'string j PK, FK "both keys"',
  'string k "just a comment"',
  // A comment that CONTAINS a comma must stay a comment, not become keys.
  'string l "one, two"',
  // The space-separated form. mermaid rejects it; recorded so the fixture says so out loud.
  'string m PK FK',
];

const rows = [];
for (const attribute of ATTRIBUTES) {
  const text = `erDiagram\n A {\n  ${attribute}\n }\n`;
  try {
    await mermaid.parse(text);
    const diagram = await mermaid.mermaidAPI.getDiagramFromText(text);
    const db = diagram.db ?? diagram.getDB();
    const entities = db.getEntities();
    const entity = entities.get ? entities.get('A') : entities.A;
    if (entity.attributes.length !== 1) {
      console.error(`${attribute}: expected one attribute, got ${entity.attributes.length}`);
      process.exit(1);
    }
    const [parsed] = entity.attributes;
    rows.push([
      attribute,
      'PARSED',
      parsed.type ?? '',
      parsed.name ?? '',
      (parsed.keys ?? []).join(),
      parsed.comment ?? '',
    ]);
  } catch (error) {
    const message = String(error?.message ?? error);
    const syntax =
      /Parse error|Expecting |Lexical error|Unrecognized text|No diagram type detected/i.test(message);
    rows.push([attribute, syntax ? 'REJECTED' : 'RUNTIME', '', '', '', '']);
  }
}

const banner = [
  '# GENERATED by scripts/headtohead/er_attribute_battery.mjs against mermaid 11.15.0 — do not hand-edit.',
  '# Each row is what the incumbent ACTUALLY parses from one attribute line of `erDiagram / A { … }`.',
  '# `keys` is joined with `,` because that is how mermaid DRAWS it: `attribute.keys.join()`.',
  ['# attribute', 'verdict', 'type', 'name', 'keys', 'comment'].join('\t'),
].join('\n');
fs.writeFileSync(OUT, `${banner}\n${rows.map((row) => row.join('\t')).join('\n')}\n`);
const composite = rows.filter((row) => row[4].includes(',')).length;
const rejected = rows.filter((row) => row[1] === 'REJECTED').length;
console.log(`${rows.length} attributes -> ${OUT}`);
console.log(`  ${composite} composite-key rows, ${rejected} rejected`);
