// Ask the PINNED incumbent what every ER relationship spelling MEANS, and write the answers down as
// the fixture `crates/fm-parser/tests/fixtures/mermaid_er_relationships.tsv`.
//
// ⚠️ THE CARDINALITIES ARE STORED CROSSED OVER, AND THAT IS THE WHOLE REASON THIS IS A GENERATOR.
// mermaid's grammar builds its relationship spec as `{ cardA: <RIGHT token>, relType, cardB: <LEFT
// token> }`. Probed on `A ||..o| B`, whose left marker is `||` and right marker is `o|`, it reports
// `cardA=ZERO_OR_ONE, cardB=ONLY_ONE` — the right marker under `cardA`. A hand-written table maps
// left-to-cardA because that is what the syntax looks like, and gets every asymmetric relationship
// backwards while every symmetric one still passes.
//
//   npm install --prefix scripts        # jsdom, already a declared devDependency there
//   node scripts/headtohead/er_relationship_battery.mjs
//
// ⚠️ NEEDS A DOM (DOMPurify); see diagram_db_probe.mjs.
//
// The battery is the CROSS PRODUCT of the three parts of the token — left marker, body, right
// marker — not a list anyone writes, for the same reason link_battery.mjs is: an asymmetric
// combination is where a spelling table silently swaps the two ends.
//
// Columns, tab separated:
//   token    the relationship as written between `A` and `B`
//   verdict  PARSED | REJECTED
//   cardA    mermaid's `cardA`   — empty unless PARSED
//   cardB    mermaid's `cardB`
//   relType  IDENTIFYING | NON_IDENTIFYING
//   from,to  the entity names as MERMAID resolved them; both are `A`/`B` for everything it accepts,
//            so a row where they are not is a marker byte eaten by an entity name
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { JSDOM } from 'jsdom';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-parser/tests/fixtures/mermaid_er_relationships.tsv');

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="c"></div></body></html>', {
  runScripts: 'dangerously',
});
const w = dom.window;
const script = w.document.createElement('script');
script.textContent = fs.readFileSync(BUNDLE, 'utf8');
w.document.head.appendChild(script);
const mermaid = w.mermaid;
if (typeof mermaid?.parse !== 'function') {
  console.error('pinned bundle did not expose window.mermaid.parse');
  process.exit(1);
}
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });

const LEFT = ['||', '|o', '}o', '}|'];
const BODY = ['--', '..'];
const RIGHT = ['||', 'o|', 'o{', '|{'];
const tokens = [];
for (const left of LEFT) {
  for (const body of BODY) {
    for (const right of RIGHT) {
      tokens.push(left + body + right);
    }
  }
}

const rows = [];
for (const token of tokens) {
  const text = `erDiagram\n  A ${token} B : rel\n`;
  try {
    await mermaid.parse(text);
    const diagram = await mermaid.mermaidAPI.getDiagramFromText(text);
    const db = diagram.db ?? diagram.getDB();
    const relationships = db.getRelationships?.() ?? db.getRelations?.() ?? [];
    if (relationships.length !== 1) {
      rows.push([token, `UNEXPECTED_${relationships.length}_RELATIONSHIPS`, '', '', '', '', '']);
      continue;
    }
    const [relationship] = relationships;
    const spec = relationship.relSpec ?? relationship;
    rows.push([
      token,
      'PARSED',
      String(spec.cardA ?? ''),
      String(spec.cardB ?? ''),
      String(spec.relType ?? ''),
      String(relationship.entityA ?? ''),
      String(relationship.entityB ?? ''),
    ]);
  } catch (error) {
    const message = String(error?.message ?? error);
    const syntax =
      /Parse error|Expecting |Lexical error|Unrecognized text|No diagram type detected/i.test(message);
    rows.push([token, syntax ? 'REJECTED' : 'RUNTIME', '', '', '', '', '']);
  }
}

const banner = [
  '# GENERATED by scripts/headtohead/er_relationship_battery.mjs against mermaid 11.15.0 — do not hand-edit.',
  '# Each row is what the incumbent ACTUALLY does with `erDiagram / A <token> B : rel`.',
  '# NOTE cardA holds the RIGHT-hand marker and cardB the LEFT-hand one; mermaid stores them crossed.',
  ['# token', 'verdict', 'cardA', 'cardB', 'relType', 'from', 'to'].join('\t'),
].join('\n');
fs.writeFileSync(OUT, `${banner}\n${rows.map((row) => row.join('\t')).join('\n')}\n`);
const parsed = rows.filter((row) => row[1] === 'PARSED').length;
console.log(`${rows.length} tokens -> ${OUT}`);
console.log(`  PARSED ${parsed}, REJECTED ${rows.filter((row) => row[1] === 'REJECTED').length}`);
