// Ask the PINNED incumbent which tags a gantt task carries, and write the answers down as the
// fixture `crates/fm-parser/tests/fixtures/mermaid_gantt_tasks.tsv`.
//
// WHY A GENERATOR AND NOT A HAND-WRITTEN TABLE. The four tags are INDEPENDENT in mermaid — its db
// threads `r.active=i.active, r.done=i.done, r.crit=i.crit, r.milestone=i.milestone` straight to the
// renderer — and that is easy to miss because every single-tag row behaves identically whether you
// model them as flags or as one enum. This parser used one enum, so `:crit, done` came out as plain
// `Done` and the critical marking silently disappeared from the bar colour AND from the accessible
// name (bd-124ew). Only a COMBINATION row can tell the two models apart, which is why the battery is
// mostly combinations.
//
//   npm install --prefix scripts        # jsdom, already a declared devDependency there
//   node scripts/headtohead/gantt_task_battery.mjs
//
// ⚠️ NEEDS A DOM (DOMPurify); see diagram_db_probe.mjs.
//
// Columns, tab separated:
//   meta       the text after the task's `:`, as written
//   verdict    PARSED | REJECTED
//   crit,done,active,milestone   mermaid's four flags, `1` or `0`
//   id         the task id mermaid resolved — auto-generated when the row declares none
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { JSDOM } from 'jsdom';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-parser/tests/fixtures/mermaid_gantt_tasks.tsv');

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="c"></div></body></html>', {
  runScripts: 'dangerously',
});
const w = dom.window;
const script = w.document.createElement('script');
script.textContent = fs.readFileSync(BUNDLE, 'utf8');
w.document.head.appendChild(script);
const mermaid = w.mermaid;
if (typeof mermaid?.parse !== 'function') {
  console.error('pinned bundle did not expose window.mermaid.parse');
  process.exit(1);
}
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });

const METAS = [
  // No tag.
  't0, 2026-01-01, 5d',
  // One tag each — the rows a single-enum model also gets right.
  'crit, t1, 2026-01-01, 5d',
  'done, t2, 2026-01-01, 5d',
  'active, t3, 2026-01-01, 5d',
  'milestone, t4, 2026-01-01, 0d',
  // COMBINATIONS — the only rows that can tell flags from an enum, in both orders because a
  // last-tag-wins parser is order-sensitive and a flag model is not.
  'crit, done, t5, 2026-01-01, 5d',
  'done, crit, t6, 2026-01-01, 5d',
  'crit, active, t7, 2026-01-01, 5d',
  'active, crit, t8, 2026-01-01, 5d',
  'crit, milestone, t9, 2026-01-01, 0d',
  'done, active, t10, 2026-01-01, 5d',
  'crit, done, active, t11, 2026-01-01, 5d',
  // Case: mermaid's keywords are lowercase in its lexer; recorded so the fixture says what it does.
  'CRIT, t12, 2026-01-01, 5d',
];

const rows = [];
for (const meta of METAS) {
  const text = `gantt\n    dateFormat YYYY-MM-DD\n    section S\n    Task :${meta}\n`;
  try {
    await mermaid.parse(text);
    const diagram = await mermaid.mermaidAPI.getDiagramFromText(text);
    const db = diagram.db ?? diagram.getDB();
    const tasks = db.getTasks() ?? [];
    if (tasks.length !== 1) {
      rows.push([meta, `UNEXPECTED_${tasks.length}_TASKS`, '', '', '', '', '']);
      continue;
    }
    const [task] = tasks;
    const bit = (value) => (value ? '1' : '0');
    rows.push([
      meta,
      'PARSED',
      bit(task.crit),
      bit(task.done),
      bit(task.active),
      bit(task.milestone),
      String(task.id ?? ''),
    ]);
  } catch (error) {
    const message = String(error?.message ?? error);
    const syntax =
      /Parse error|Expecting |Lexical error|Unrecognized text|No diagram type detected/i.test(message);
    rows.push([meta, syntax ? 'REJECTED' : 'RUNTIME', '', '', '', '', '']);
  }
}

const banner = [
  '# GENERATED by scripts/headtohead/gantt_task_battery.mjs against mermaid 11.15.0 — do not hand-edit.',
  '# Each row is the tag set the incumbent builds from one `Task :<meta>` line.',
  '# The four tags are INDEPENDENT; a combination row is the only kind that catches a single-enum model.',
  ['# meta', 'verdict', 'crit', 'done', 'active', 'milestone', 'id'].join('\t'),
].join('\n');
fs.writeFileSync(OUT, `${banner}\n${rows.map((row) => row.join('\t')).join('\n')}\n`);
const combos = rows.filter(
  (row) => row[1] === 'PARSED' && [row[2], row[3], row[4], row[5]].filter((bit) => bit === '1').length > 1,
).length;
console.log(`${rows.length} tasks -> ${OUT}`);
console.log(`  ${combos} multi-tag rows`);
