// Ask the PINNED incumbent what every flowchart link spelling MEANS, and write the answers down as
// the fixture `crates/fm-parser/tests/fixtures/mermaid_flow_links.tsv`.
//
// WHY A GENERATOR AND NOT A HAND-WRITTEN TABLE. The fixture is the differential oracle for
// `flowchart_link_differential.rs`, so a hand-authored row would be a claim about mermaid rather
// than a measurement of it — and the whole defect class this covers (bd-lrl48) came from exactly
// that: a table of link spellings written from what the syntax LOOKS like. mermaid's own answer for
// `o==>` is `arrow_point` / stroke `normal`, which nobody guesses.
//
//   node scripts/headtohead/link_battery.mjs
//
// The battery is the CROSS PRODUCT of the three parts of mermaid's link grammar — head marker, body
// run, tail marker — rather than a list of links anyone would write. Combinations nobody writes are
// the point: `o===x` and `x-..-o` are where a spelling table silently loses either the marker or the
// weight, and the parser then leaves the orphaned byte on the ENDPOINT (`A o=== B` used to build a
// node called `A_o`). Body runs go past the longest literal any table could hold, because the
// grammar's run is unbounded.
//
// Columns, tab separated:
//   token     the link as written between `A` and `B`
//   verdict   PARSED | REJECTED | RUNTIME (see parse_probe.mjs for what the three mean)
//   type      mermaid's edge type   (arrow_open / arrow_point / arrow_circle / arrow_cross,
//             each optionally `double_`-prefixed) — empty unless PARSED
//   stroke    mermaid's stroke      (normal / thick / dotted) — empty unless PARSED
//   start,end the edge's endpoints as MERMAID resolved them. These are the columns that catch a
//             link byte eaten by a node id; both are `A`/`B` for every token mermaid accepts.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import vm from 'node:vm';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-parser/tests/fixtures/mermaid_flow_links.tsv');

const ctx = { console, setTimeout, clearTimeout, queueMicrotask, TextEncoder, TextDecoder, URL };
ctx.globalThis = ctx;
ctx.self = ctx;
ctx.window = ctx;
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(BUNDLE, 'utf8'), ctx);
const mermaid = ctx.__esbuild_esm_mermaid_nm.mermaid.default ?? ctx.__esbuild_esm_mermaid_nm.mermaid;

const HEADS = ['', 'o', 'x', '<'];
const BODIES = ['--', '---', '----', '-----', '==', '===', '====', '-.-', '-..-', '-...-', '.-'];
const TAILS = ['', '>', 'o', 'x'];

const rows = [];
for (const head of HEADS) {
  for (const body of BODIES) {
    for (const tail of TAILS) {
      const token = head + body + tail;
      const text = `flowchart LR\n  A ${token} B\n`;
      try {
        await mermaid.parse(text);
        // `parse` only says the grammar accepted it. The MEANING lives in the diagram's db, which
        // is why this goes back through getDiagramFromText rather than trusting the parse verdict.
        const diagram = await mermaid.mermaidAPI.getDiagramFromText(text);
        const db = diagram.db ?? diagram.getDB();
        const edges = db.getEdges();
        if (edges.length !== 1) {
          rows.push([token, `UNEXPECTED_${edges.length}_EDGES`, '', '', '', '']);
          continue;
        }
        const [edge] = edges;
        rows.push([token, 'PARSED', edge.type, edge.stroke, edge.start, edge.end]);
      } catch (err) {
        const message = String(err?.message ?? err);
        // The grammar's own rejection text; see parse_probe.mjs on why matching these strings —
        // and not a list of DOM-ish words — is what survives minification.
        const syntax =
          /Parse error|Expecting |Lexical error|Unrecognized text|No diagram type detected/i.test(
            message
          );
        rows.push([token, syntax ? 'REJECTED' : 'RUNTIME', '', '', '', '']);
      }
    }
  }
}

const header = ['# token', 'verdict', 'type', 'stroke', 'start', 'end'].join('\t');
const banner = [
  '# GENERATED by scripts/headtohead/link_battery.mjs against mermaid 11.15.0 — do not hand-edit.',
  '# Each row is what the incumbent ACTUALLY does with `flowchart LR / A <token> B`.',
  header,
].join('\n');
fs.writeFileSync(OUT, `${banner}\n${rows.map((row) => row.join('\t')).join('\n')}\n`);

const parsed = rows.filter((row) => row[1] === 'PARSED').length;
console.log(`${rows.length} tokens -> ${OUT}`);
console.log(`  PARSED ${parsed}, REJECTED ${rows.filter((r) => r[1] === 'REJECTED').length}`);
