// Ask the PINNED incumbent what percentage it labels each pie slice with, and write the answers to
// `crates/fm-render-svg/tests/fixtures/mermaid_pie_percents.tsv`.
//
// ⚠️ THE ROUNDING IS THE WHOLE POINT, AND IT IS NOT THE ROUNDING RUST DEFAULTS TO. mermaid rounds in
// JavaScript, where `Math.round(12.5)` is `13`. Rust's `{:.0}` rounds half to EVEN and renders the
// same value as `12`. The difference appears only on an exact half, so a `{:.0}` implementation
// agrees on 40/30/30, on 1/1/1 and on 2/1, and disagrees on 1/8. The battery therefore carries
// EXACT-HALF cases deliberately; a table of round numbers cannot tell the two rules apart.
//
//   npm install --prefix scripts        # jsdom, already a declared devDependency there
//   node scripts/headtohead/pie_percent_battery.mjs
//
// ⚠️ NEEDS A DOM, and mermaid's pie renderer additionally needs SVG measurement jsdom lacks. The
// stubs below let the render COMPLETE; they make its geometry fiction, which is why this reads only
// the text. See drawn_text_diff.mjs for the same caveat at length.
//
// Columns, tab separated:
//   values    the slice values, comma separated, in source order
//   percents  the percentage labels mermaid drew, comma separated, in the order it drew them
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { JSDOM } from 'jsdom';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-render-svg/tests/fixtures/mermaid_pie_percents.tsv');

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="c"></div></body></html>', {
  runScripts: 'dangerously',
  pretendToBeVisual: true,
});
const w = dom.window;
for (const name of ['TextEncoder', 'TextDecoder', 'crypto', 'structuredClone', 'DOMRect']) {
  if (!w[name] && globalThis[name]) w[name] = globalThis[name];
}
for (const proto of [w.SVGElement.prototype, w.Element.prototype]) {
  if (!proto.getBBox) proto.getBBox = () => ({ x: 0, y: 0, width: 0, height: 0 });
  if (!proto.getComputedTextLength) proto.getComputedTextLength = () => 0;
  if (!proto.getSubStringLength) proto.getSubStringLength = () => 0;
  if (!proto.getScreenCTM) proto.getScreenCTM = () => ({ a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 });
}
const script = w.document.createElement('script');
script.textContent = fs.readFileSync(BUNDLE, 'utf8');
w.document.head.appendChild(script);
const mermaid = w.mermaid;
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });

// Round numbers first, then the exact halves that separate half-up from half-to-even:
//   1/8 = 12.5   -> half-up 13, half-to-even 12   <- the discriminating case
//   3/8 = 37.5   -> both 38
//   1/40 = 2.5   -> half-up 3,  half-to-even 2
const CASES = [
  [40, 30, 30],
  [1, 1, 1],
  [2, 1],
  [1, 7],
  [3, 5],
  [1, 39],
  [1, 2, 3, 4],
  [100],
  [1, 1, 1, 1, 1, 1],
];

const rows = [];
for (const values of CASES) {
  const source = `pie title T\n${values.map((v, i) => `  "S${i}" : ${v}`).join('\n')}\n`;
  const { svg } = await mermaid.render(`pie${values.join('_')}`, source);
  const percents = [...svg.matchAll(/<text[^>]*>([^<]*)<\/text>/g)]
    .map((m) => m[1].trim())
    .filter((text) => /^\d+%$/.test(text));
  rows.push([values.join(','), percents.join(',')].join('\t'));
}

const header = ['values', 'percents'].join('\t');
fs.writeFileSync(OUT, `# GENERATED by scripts/headtohead/pie_percent_battery.mjs against mermaid 11.15.0 — do not hand-edit.\n${header}\n${rows.join('\n')}\n`);
console.log(`${OUT}: ${rows.length} rows`);
for (const row of rows) console.log(`  ${row}`);
