// Ask the PINNED incumbent what every sequence-message arrow spelling MEANS, and write the answers
// down as the fixture `crates/fm-parser/tests/fixtures/mermaid_sequence_arrows.tsv`, beside
// `mermaid_flow_links.tsv` — this is a parser contract, no rendering involved.
//
// The 2026-08-25 sweep showed all 28 sequence constructs agree with the incumbent on ACTOR and
// MESSAGE COUNTS. Counts are the cheap half. What a message COUNTS as — solid or dotted, arrowhead
// or cross or open circle, one-way or bidirectional — is carried by mermaid's numeric `type` code,
// and a wrong code is a message drawn with the wrong line and the wrong head while every count still
// agrees. That is the same defect shape the flowchart link battery caught (bd-lrl48).
//
//   npm install --prefix scripts        # jsdom, already a declared devDependency there
//   node scripts/headtohead/sequence_arrow_battery.mjs
//
// ⚠️ NEEDS A DOM (DOMPurify); see diagram_db_probe.mjs.
//
// The battery is a CROSS PRODUCT of the three parts of the arrow — head marker, body run, tail
// marker — not a list of arrows anyone writes, for the same reason link_battery.mjs is: the
// combinations nobody writes are where a spelling table silently loses the weight or the head.
//
// Columns, tab separated:
//   token    the arrow as written between `A` and `B`
//   verdict  PARSED | REJECTED | RUNTIME (see parse_probe.mjs)
//   type     mermaid's numeric message type code — empty unless PARSED
//   name     that code's name in mermaid's own LINETYPE table, so the fixture is readable
//   from,to  the endpoints as MERMAID resolved them; both are `A`/`B` for every token it accepts,
//            so a row where they are not is an arrow byte that got eaten by an actor name
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { JSDOM } from 'jsdom';

const BUNDLE = '/home/ubuntu/.cache/fm-headtohead/mermaid-11.15.0.min.js';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../crates/fm-parser/tests/fixtures/mermaid_sequence_arrows.tsv');

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="c"></div></body></html>', {
  runScripts: 'dangerously',
});
const w = dom.window;
const script = w.document.createElement('script');
script.textContent = fs.readFileSync(BUNDLE, 'utf8');
w.document.head.appendChild(script);
const mermaid = w.mermaid;
if (typeof mermaid?.parse !== 'function') {
  console.error('pinned bundle did not expose window.mermaid.parse');
  process.exit(1);
}
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });

const HEADS = ['', '<<'];
const BODIES = ['-', '--'];
const TAILS = ['>', '>>', 'x', ')', '->>', '-->>'];
const tokens = new Set();
for (const head of HEADS) {
  for (const body of BODIES) {
    for (const tail of TAILS) {
      tokens.add(head + body + tail);
    }
  }
}
// The ten documented spellings, in case the cross product's shape ever drifts away from them.
for (const token of ['->', '-->', '->>', '-->>', '-x', '--x', '-)', '--)', '<<->>', '<<-->>']) {
  tokens.add(token);
}

/** mermaid's own LINETYPE table, so a numeric code in the fixture is readable by a human. */
async function lineTypeNames() {
  const probe = 'sequenceDiagram\nA ->> B: m';
  await mermaid.parse(probe);
  const diagram = await mermaid.mermaidAPI.getDiagramFromText(probe);
  const db = diagram.db ?? diagram.getDB();
  const table = db.LINETYPE ?? db.getLineType?.() ?? {};
  const names = new Map();
  for (const [name, value] of Object.entries(table)) {
    if (typeof value === 'number' && !names.has(value)) names.set(value, name);
  }
  return names;
}
const NAMES = await lineTypeNames();

const rows = [];
for (const token of [...tokens].sort()) {
  const text = `sequenceDiagram\nA ${token} B: m\n`;
  try {
    await mermaid.parse(text);
    const diagram = await mermaid.mermaidAPI.getDiagramFromText(text);
    const db = diagram.db ?? diagram.getDB();
    const messages = (db.getMessages() ?? []).filter((message) => message.from && message.to);
    if (messages.length !== 1) {
      rows.push([token, `UNEXPECTED_${messages.length}_MESSAGES`, '', '', '', '']);
      continue;
    }
    const [message] = messages;
    rows.push([
      token,
      'PARSED',
      String(message.type),
      NAMES.get(message.type) ?? '',
      String(message.from),
      String(message.to),
    ]);
  } catch (error) {
    const text = String(error?.message ?? error);
    const syntax = /Parse error|Expecting |Lexical error|Unrecognized text|No diagram type detected/i.test(text);
    rows.push([token, syntax ? 'REJECTED' : 'RUNTIME', '', '', '', '']);
  }
}

const banner = [
  '# GENERATED by scripts/headtohead/sequence_arrow_battery.mjs against mermaid 11.15.0 — do not hand-edit.',
  '# Each row is what the incumbent ACTUALLY does with `sequenceDiagram / A <token> B: m`.',
  ['# token', 'verdict', 'type', 'name', 'from', 'to'].join('\t'),
].join('\n');
fs.writeFileSync(OUT, `${banner}\n${rows.map((row) => row.join('\t')).join('\n')}\n`);
const parsed = rows.filter((row) => row[1] === 'PARSED').length;
console.log(`${rows.length} tokens -> ${OUT}`);
console.log(`  PARSED ${parsed}, REJECTED ${rows.filter((row) => row[1] === 'REJECTED').length}`);
