//! The bench generators that claim to mirror the head-to-head corpus must actually do it (bd-9cma).
//!
//! Before this test the claim lived only in doc comments, and two of the three were false —
//! `gen_dense_dag` used a different direction, different node ids and a different edge step, and
//! `gen_cyclic_scc` used labels wide enough to change node sizing. Nothing failed, because nothing
//! checked: the criterion harness and the head-to-head harness each measured their own document and
//! both were internally consistent. That is a worse failure than two harnesses disagreeing on one
//! input, and no A/A null can see it.
//!
//! The generators are compiled FROM THE BENCH'S OWN SOURCE via `#[path]`, so this cannot drift by
//! someone editing one copy: there is only one copy. A criterion bench runs with `harness = false`,
//! so a `#[cfg(test)]` module inside the bench would never run, which is why the check lives here.
//!
//! Fixtures are generated by the authoritative side — `scripts/headtohead/corpus.mjs` — and
//! committed. Regenerate them only when the CORPUS deliberately changes, and expect that to
//! re-baseline both harnesses at once, which is the point.

#[path = "../benches/corpus_generators.rs"]
mod corpus_generators;

use corpus_generators::{gen_cyclic_scc, gen_dense_dag, gen_wide};

/// Read a committed corpus fixture by its corpus id.
fn fixture(id: &str) -> String {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/corpus_parity/");
    let text = std::fs::read_to_string(format!("{path}{id}.mmd")).unwrap_or_default();
    assert!(
        !text.is_empty(),
        "missing or empty corpus fixture {id}.mmd — regenerate it from scripts/headtohead/corpus.mjs, \
         never from the bench"
    );
    text
}

/// The first line at which two documents differ, as `(line number, bench line, corpus line)`.
///
/// Reported rather than a whole-document diff because these fixtures run to 12,592 bytes and the
/// first differing line is almost always the entire story: a direction, an id prefix, a label.
fn first_difference(generated: &str, expected: &str) -> Option<(usize, String, String)> {
    let mut generated_lines = generated.lines();
    let mut expected_lines = expected.lines();
    let mut line_number = 1;
    loop {
        return match (generated_lines.next(), expected_lines.next()) {
            (None, None) => None,
            (Some(got), Some(want)) if got == want => {
                line_number += 1;
                continue;
            }
            (got, want) => Some((
                line_number,
                got.unwrap_or("<end of bench output>").to_owned(),
                want.unwrap_or("<end of corpus fixture>").to_owned(),
            )),
        };
    }
}

fn assert_mirrors(id: &str, generated: &str) {
    let expected = fixture(id);
    let Some((line_number, got, want)) = first_difference(generated, &expected) else {
        // Equal line by line; make the byte-level claim explicit rather than implied.
        assert_eq!(
            generated.len(),
            expected.len(),
            "{id}: every line matches but the byte lengths differ (trailing newline?)"
        );
        return;
    };
    assert_eq!(
        got,
        want,
        "\n{id}: bench generator no longer mirrors the corpus fixture, first difference at line \
         {line_number} (bench {} bytes / corpus {} bytes).\nEither restore the mirror, or rename \
         the generator so it stops claiming one.\n",
        generated.len(),
        expected.len(),
    );
}

#[test]
fn wide_generator_mirrors_the_corpus() {
    // The one pair that was already correct. Pinned so it stays that way — it is the fixture
    // bd-8bbq's three-harness cross-check depends on being able to trust.
    assert_mirrors("wide_8x16", &gen_wide(8, 16));
    assert_mirrors("wide_12x24", &gen_wide(12, 24));
    assert_mirrors("wide_16x32", &gen_wide(16, 32));
}

#[test]
fn dense_dag_generator_mirrors_the_corpus() {
    assert_mirrors("dense_dag_200", &gen_dense_dag(200, 4));
}

#[test]
fn cyclic_scc_generator_mirrors_the_corpus() {
    assert_mirrors("cyclic_scc_100", &gen_cyclic_scc(100, 5));
}

/// The fixtures must be the corpus, not a copy of whatever the bench happened to emit.
///
/// This is the control for the three tests above. If someone "fixes" a parity failure by
/// regenerating the fixture from the bench, every assertion above passes again while the two
/// harnesses drift apart exactly as before — the failure mode this whole test exists to prevent.
/// The three properties below are corpus facts, taken from `corpus.mjs`, that the pre-bd-9cma bench
/// generators violated. They cannot be satisfied by a fixture captured from the old bench.
#[test]
fn fixtures_carry_the_corpus_shape_not_the_old_bench_shape() {
    let dense = fixture("dense_dag_200");
    assert!(
        dense.starts_with("flowchart LR"),
        "dense_dag_200 must be LR, as corpus.mjs denseDag emits; the old bench used TD"
    );
    assert!(
        dense.contains("  D0[D0]") && !dense.contains("[Node "),
        "dense_dag_200 must use D{{i}}[D{{i}}] ids; the old bench used N{{i}}[Node {{i}}]"
    );
    assert!(
        dense.contains("  D0-->D4") && !dense.contains("  D0-->D5"),
        "dense_dag_200 fans out over 1..=4; the old bench stepped [1, 2, 3, 5]"
    );

    let cyclic = fixture("cyclic_scc_100");
    assert!(
        cyclic.contains("  C0[C0]") && !cyclic.contains("[Node "),
        "cyclic_scc_100 must use C{{i}}[C{{i}}] labels; the old bench used C{{i}}[Node {{i}}]"
    );
}
